export const ADD_FAVORITES = "ADD_FAVORITES"
export const DELETE_FAVORITES = "DELETE_FAVORITES"
export const FILTER_FAVORITES = 'FILTER_FAVORITES';
export const ORDER_FAVORITES = 'ORDER_FAVORITES';
export const RESET_FAVORITES = 'RESET_FAVORITES';